version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.8
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.8
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    networks:
      - elastic
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.8
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
    networks:
      - elastic

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.8
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./logstash.conf:/etc/logstash/conf.d/logstash.conf
    ports:
      - 5044:5044
    depends_on:
      - es01
    networks:
      - elastic


  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.8
    environment:
      - ELASTICSEARCH_HOSTS=http://es01:9200
    ports:
      - 5601:5601
    depends_on:
      - es01
    networks:
      - elastic

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  elastic:
    driver: bridge

# version: '3.7'
# services:
#   elasticsearch:
#     image: docker.elastic.co/elasticsearch/elasticsearch:7.17.8
#     environment:
#       - discovery.type=single-node
#       - cluster.name=elk-cluster
#       - xpack.security.enabled=false
#       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#     ulimits:
#       memlock:
#         soft: -1
#         hard: -1
#     ports:
#       - 9200:9200
#       - 9300:9300
#     volumes:
#       - esdata:/usr/share/elasticsearch/data
#     networks:
#       - elastic

#   logstash:
#     image: docker.elastic.co/logstash/logstash:7.17.8
#     command: logstash -f /etc/logstash/conf.d/logstash.conf
#     volumes:
#       - ./logstash.conf:/etc/logstash/conf.d/logstash.conf
#     ports:
#       - 5044:5044
#     depends_on:
#       - elasticsearch
#     networks:
#       - elastic


#   kibana:
#     image: docker.elastic.co/kibana/kibana:7.17.8
#     environment:
#       - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
#     ports:
#       - 5601:5601
#     depends_on:
#       - elasticsearch
#     networks:
#       - elastic

# networks:
#   elastic:
#     driver: bridge

# volumes:
#   esdata:
